
name: Create Binaries for Windows

on: 
  push:
    tags:
    - '*win'


jobs:
  deploy:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build binary
      run: pyinstaller --onefile starrem2k13.py -i starrem.ico
    - name: copy weights
      run: xcopy weights\* dist\weights\ /E
    - name: copy other files
      run: |
           xcopy LICENSE dist\ /E
           xcopy releasenotes.md dist\ /E
    - uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'starrem2k13_win.zip'
        directory: 'dist/'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/starrem2k13_win.zip"
        bodyFile: "releasenotes.md"
